#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

waybar &

# Note: the "$SUPER" modifier is also known as Logo, GUI, Windows, Mod4, etc.
SUPER=Mod1

riverctl map normal $SUPER r 

# $SUPER+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $SUPER Grave spawn "foot -e tmux new-session -A -s workspace"

# $SUPER+Q to close the focused view
riverctl map normal $SUPER Q close

# $SUPER+Shift+E to exit river
riverctl map normal $SUPER+Shift E exit

# $SUPER+J and $SUPER+K to focus the next/previous view in the layout stack
riverctl map normal $SUPER h focus-view left
riverctl map normal $SUPER j focus-view down
riverctl map normal $SUPER k focus-view up
riverctl map normal $SUPER l focus-view right

# $SUPER+Shift+J and $SUPER+Shift+K to swap the focused view with the next/previous
# view in the layout stack
# riverctl map normal $SUPER+Shift J swap next
# riverctl map normal $SUPER+Shift K swap previous

# $SUPER+Period and $SUPER+Comma to focus the next/previous output
riverctl map normal $SUPER Period focus-output next
riverctl map normal $SUPER Comma focus-output previous

# $SUPER+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $SUPER+Shift Period send-to-output next
riverctl map normal $SUPER+Shift Comma send-to-output previous

# $SUPER+Return to bump the focused view to the top of the layout stack
riverctl map normal $SUPER Return zoom

# $SUPER+H and $SUPER+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $SUPER Minus send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $SUPER Equal send-layout-cmd rivertile "main-ratio +0.05"

# $SUPER+Shift+H and $SUPER+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal $SUPER+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal $SUPER+Shift L send-layout-cmd rivertile "main-count -1"

# $SUPER+Alt+{H,J,K,L} to move views
riverctl map normal $SUPER+Shift H move left 100
riverctl map normal $SUPER+Shift J move down 100
riverctl map normal $SUPER+Shift K move up 100
riverctl map normal $SUPER+Shift L move right 100

# $SUPER+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal $SUPER+Alt+Control H snap left
# riverctl map normal $SUPER+Alt+Control J snap down
# riverctl map normal $SUPER+Alt+Control K snap up
# riverctl map normal $SUPER+Alt+Control L snap right

# $SUPER+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal $SUPER+Alt+Shift H resize horizontal -100
# riverctl map normal $SUPER+Alt+Shift J resize vertical 100
# riverctl map normal $SUPER+Alt+Shift K resize vertical -100
# riverctl map normal $SUPER+Alt+Shift L resize horizontal 100

# $SUPER + Left Mouse Button to move views
riverctl map-pointer normal $SUPER BTN_LEFT move-view

# $SUPER + Right Mouse Button to resize views
riverctl map-pointer normal $SUPER BTN_RIGHT resize-view

# $SUPER + Middle Mouse Button to toggle float
riverctl map-pointer normal $SUPER BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # $SUPER+[1-9] to focus tag [0-8]
    riverctl map normal $SUPER $i set-focused-tags $tags

    # $SUPER+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $SUPER+Shift $i set-view-tags $tags

    # $SUPER+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $SUPER+Control $i toggle-focused-tags $tags

    # $SUPER+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $SUPER+Shift+Control $i toggle-view-tags $tags
done

# $SUPER+0 to focus all tags
# $SUPER+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $SUPER 0 set-focused-tags $all_tags
riverctl map normal $SUPER+Shift 0 set-view-tags $all_tags

# $SUPER+Space to toggle float
riverctl map normal $SUPER Space toggle-float

# $SUPER+F to toggle fullscreen
riverctl map normal $SUPER F toggle-fullscreen

# $SUPER+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $SUPER Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $SUPER Right send-layout-cmd rivertile "main-location right"
riverctl map normal $SUPER Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $SUPER Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# $SUPER+F11 to enter passthrough mode
riverctl map normal $SUPER F11 enter-mode passthrough

# $SUPER+F11 to return to normal mode
riverctl map passthrough $SUPER F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 6 &
