vim.keymap.set({ 'n', 'v' }, '<leader>c', '<Plug>NERDCommenterToggle')
local builtin = require('telescope.builtin')
local telescope = require('telescope')
telescope.load_extension('dap')
-- telescope.load_extension('colorscheme')
local datscope = telescope.extensions.dap
vim.keymap.set('n', '<leader>f', builtin.lsp_dynamic_workspace_symbols, {})
vim.keymap.set('n', '<leader>d', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>e', builtin.lsp_references, {})
vim.keymap.set('n', '<leader>s', builtin.find_files, {})
vim.keymap.set('n', '<leader>a', builtin.git_files, {})
vim.keymap.set('n', '<leader>g', builtin.live_grep, {})
vim.keymap.set('n', '<leader>b', builtin.buffers, {})
vim.keymap.set('n', '<leader>h', builtin.help_tags, {})
vim.keymap.set('n', '<leader>n', datscope.configurations, {})
-- vim.keymap.set('n', '<leader>m', datscope.breakpoints, {})
