"$schema" = "https://starship.rs/config-schema.json"

format = "$directory$git_branch$git_status$git_state$cmd_duration$status$username"
# right_format = "$cmd_duration$status"
add_newline = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[username]
style_root = "red"
style_user = "yellow"
show_always = true
format = "[$user]($style) "
aliases = { shirshov = "%", pinbraerts = "%", dima = "%", root = "$", wheel = "$", admin = "$" }

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "purple"

[git_status]
modified = "[*](yellow)"
staged = "[+](green)"
deleted = "[-](red)"
untracked = "?"
conflicted = "[=](red)"
ahead = "[↑](green)"
behind = "[↓](red)"
renamed = "[→](yellow)"
format = "$all_status$ahead_behind "

[directory]
use_os_path_sep = false
truncation_length = 100
truncate_to_repo = false
style = "cyan"

[status]
format = "[$status]($symbol) "
disabled = false
success_symbol = "green"
symbol = "red"

[character]
success_symbol = "[%](yellow)"
error_symbol = "[%](yellow)"
vimcmd_symbol = "[%](yellow)"
vimcmd_visual_symbol = "[%](yellow)"
vimcmd_replace_one_symbol = "[%](yellow)"
vimcmd_replace_symbol = "[%](yellow)"
